#NORUN Updated with check commit

diff --git a/.github/workflows/main.yaml b/.github/workflows/main.yaml
--- a/.github/workflows/main.yaml
+++ b/.github/workflows/main.yaml
@@ -9,18 +9,18 @@ jobs:
         runs-on: ubuntu-latest
 
         steps:
-        - name: Check Commit Message
-        id: check_commit
-        run: |
-          if [[ $(git log --format=%B -n 1 ${{ github.sha }}) == \#NORUN* ]]; then
-            echo "Commit message starts with #NORUN, exiting workflow."
-            exit 78 # 78 is a neutral exit code indicating that the workflow was intentionally canceled.
-          fi
-          
         - name: checkout my source
           id: check_out_mysource
           uses: actions/checkout@v4
         
+        - name: Check Commit Message
+          id: check_commit
+          run: |
+            if [[ $(git log --format=%B -n 1 ${{ github.sha }}) == \#NORUN* ]]; then
+              echo "Commit message starts with #NORUN, exiting workflow."
+              exit 78 # 78 is a neutral exit code indicating that the workflow was intentionally canceled.
+            fi 
+
         - name: trivy scan
           id: trivy_scan
           uses: aquasecurity/trivy-action@master
